/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DonRouteImport } from './routes/don'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as GouvernanceRouteImport } from './routes/gouvernance'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as PdimaRouteImport } from './routes/pdima'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminActualitesRouteImport } from './routes/admin/actualites'
import { Route as AdminDocumentsRouteImport } from './routes/admin/documents'
import { Route as AdminGalerieRouteImport } from './routes/admin/galerie'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminMessagesRouteImport } from './routes/admin/messages'
import { Route as AdminPagesRouteImport } from './routes/admin/pages'
import { Route as ApiMessagesRouteImport } from './routes/api/messages'
import { Route as ApiNotifyAdminLoginRouteImport } from './routes/api/notify-admin-login'
import { Route as ApiVisitsRouteImport } from './routes/api/visits'
import { Route as ApiCmsDocumentsRouteImport } from './routes/api/cms/documents'
import { Route as ApiCmsGalleryRouteImport } from './routes/api/cms/gallery'
import { Route as ApiCmsNewsRouteImport } from './routes/api/cms/news'
import { Route as ApiCmsPagesRouteImport } from './routes/api/cms/pages'
import { Route as ApiStripeWebhookRouteImport } from './routes/api/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DonRoute = DonRouteImport.update({
  id: '/don',
  path: '/don',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const GouvernanceRoute = GouvernanceRouteImport.update({
  id: '/gouvernance',
  path: '/gouvernance',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const PdimaRoute = PdimaRouteImport.update({
  id: '/pdima',
  path: '/pdima',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActualitesRoute = AdminActualitesRouteImport.update({
  id: '/admin/actualites',
  path: '/admin/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDocumentsRoute = AdminDocumentsRouteImport.update({
  id: '/admin/documents',
  path: '/admin/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGalerieRoute = AdminGalerieRouteImport.update({
  id: '/admin/galerie',
  path: '/admin/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/admin/pages',
  path: '/admin/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMessagesRoute = ApiMessagesRouteImport.update({
  id: '/api/messages',
  path: '/api/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotifyAdminLoginRoute = ApiNotifyAdminLoginRouteImport.update({
  id: '/api/notify-admin-login',
  path: '/api/notify-admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisitsRoute = ApiVisitsRouteImport.update({
  id: '/api/visits',
  path: '/api/visits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsDocumentsRoute = ApiCmsDocumentsRouteImport.update({
  id: '/api/cms/documents',
  path: '/api/cms/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsGalleryRoute = ApiCmsGalleryRouteImport.update({
  id: '/api/cms/gallery',
  path: '/api/cms/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsNewsRoute = ApiCmsNewsRouteImport.update({
  id: '/api/cms/news',
  path: '/api/cms/news',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCmsPagesRoute = ApiCmsPagesRouteImport.update({
  id: '/api/cms/pages',
  path: '/api/cms/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/don': typeof DonRoute
  '/faq': typeof FaqRoute
  '/gouvernance': typeof GouvernanceRoute
  '/impact': typeof ImpactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pdima': typeof PdimaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/notify-admin-login': typeof ApiNotifyAdminLoginRoute
  '/api/visits': typeof ApiVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cms/documents': typeof ApiCmsDocumentsRoute
  '/api/cms/gallery': typeof ApiCmsGalleryRoute
  '/api/cms/news': typeof ApiCmsNewsRoute
  '/api/cms/pages': typeof ApiCmsPagesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/don': typeof DonRoute
  '/faq': typeof FaqRoute
  '/gouvernance': typeof GouvernanceRoute
  '/impact': typeof ImpactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pdima': typeof PdimaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/notify-admin-login': typeof ApiNotifyAdminLoginRoute
  '/api/visits': typeof ApiVisitsRoute
  '/admin': typeof AdminIndexRoute
  '/api/cms/documents': typeof ApiCmsDocumentsRoute
  '/api/cms/gallery': typeof ApiCmsGalleryRoute
  '/api/cms/news': typeof ApiCmsNewsRoute
  '/api/cms/pages': typeof ApiCmsPagesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/actualites': typeof ActualitesRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/don': typeof DonRoute
  '/faq': typeof FaqRoute
  '/gouvernance': typeof GouvernanceRoute
  '/impact': typeof ImpactRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/pdima': typeof PdimaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/actualites': typeof AdminActualitesRoute
  '/admin/documents': typeof AdminDocumentsRoute
  '/admin/galerie': typeof AdminGalerieRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/pages': typeof AdminPagesRoute
  '/api/messages': typeof ApiMessagesRoute
  '/api/notify-admin-login': typeof ApiNotifyAdminLoginRoute
  '/api/visits': typeof ApiVisitsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/cms/documents': typeof ApiCmsDocumentsRoute
  '/api/cms/gallery': typeof ApiCmsGalleryRoute
  '/api/cms/news': typeof ApiCmsNewsRoute
  '/api/cms/pages': typeof ApiCmsPagesRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/confidentialite'
    | '/contact'
    | '/documents'
    | '/don'
    | '/faq'
    | '/gouvernance'
    | '/impact'
    | '/mentions-legales'
    | '/pdima'
    | '/sitemap.xml'
    | '/admin/actualites'
    | '/admin/documents'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/api/messages'
    | '/api/notify-admin-login'
    | '/api/visits'
    | '/admin/'
    | '/api/cms/documents'
    | '/api/cms/gallery'
    | '/api/cms/news'
    | '/api/cms/pages'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/confidentialite'
    | '/contact'
    | '/documents'
    | '/don'
    | '/faq'
    | '/gouvernance'
    | '/impact'
    | '/mentions-legales'
    | '/pdima'
    | '/sitemap.xml'
    | '/admin/actualites'
    | '/admin/documents'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/api/messages'
    | '/api/notify-admin-login'
    | '/api/visits'
    | '/admin'
    | '/api/cms/documents'
    | '/api/cms/gallery'
    | '/api/cms/news'
    | '/api/cms/pages'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/actualites'
    | '/confidentialite'
    | '/contact'
    | '/documents'
    | '/don'
    | '/faq'
    | '/gouvernance'
    | '/impact'
    | '/mentions-legales'
    | '/pdima'
    | '/sitemap.xml'
    | '/admin/actualites'
    | '/admin/documents'
    | '/admin/galerie'
    | '/admin/login'
    | '/admin/messages'
    | '/admin/pages'
    | '/api/messages'
    | '/api/notify-admin-login'
    | '/api/visits'
    | '/admin/'
    | '/api/cms/documents'
    | '/api/cms/gallery'
    | '/api/cms/news'
    | '/api/cms/pages'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  ActualitesRoute: typeof ActualitesRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  DonRoute: typeof DonRoute
  FaqRoute: typeof FaqRoute
  GouvernanceRoute: typeof GouvernanceRoute
  ImpactRoute: typeof ImpactRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PdimaRoute: typeof PdimaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminActualitesRoute: typeof AdminActualitesRoute
  AdminDocumentsRoute: typeof AdminDocumentsRoute
  AdminGalerieRoute: typeof AdminGalerieRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPagesRoute: typeof AdminPagesRoute
  ApiMessagesRoute: typeof ApiMessagesRoute
  ApiNotifyAdminLoginRoute: typeof ApiNotifyAdminLoginRoute
  ApiVisitsRoute: typeof ApiVisitsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiCmsDocumentsRoute: typeof ApiCmsDocumentsRoute
  ApiCmsGalleryRoute: typeof ApiCmsGalleryRoute
  ApiCmsNewsRoute: typeof ApiCmsNewsRoute
  ApiCmsPagesRoute: typeof ApiCmsPagesRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don': {
      id: '/don'
      path: '/don'
      fullPath: '/don'
      preLoaderRoute: typeof DonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gouvernance': {
      id: '/gouvernance'
      path: '/gouvernance'
      fullPath: '/gouvernance'
      preLoaderRoute: typeof GouvernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pdima': {
      id: '/pdima'
      path: '/pdima'
      fullPath: '/pdima'
      preLoaderRoute: typeof PdimaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/actualites': {
      id: '/admin/actualites'
      path: '/admin/actualites'
      fullPath: '/admin/actualites'
      preLoaderRoute: typeof AdminActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/documents': {
      id: '/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AdminDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/galerie': {
      id: '/admin/galerie'
      path: '/admin/galerie'
      fullPath: '/admin/galerie'
      preLoaderRoute: typeof AdminGalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/admin/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/messages': {
      id: '/api/messages'
      path: '/api/messages'
      fullPath: '/api/messages'
      preLoaderRoute: typeof ApiMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notify-admin-login': {
      id: '/api/notify-admin-login'
      path: '/api/notify-admin-login'
      fullPath: '/api/notify-admin-login'
      preLoaderRoute: typeof ApiNotifyAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/visits': {
      id: '/api/visits'
      path: '/api/visits'
      fullPath: '/api/visits'
      preLoaderRoute: typeof ApiVisitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/documents': {
      id: '/api/cms/documents'
      path: '/api/cms/documents'
      fullPath: '/api/cms/documents'
      preLoaderRoute: typeof ApiCmsDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/gallery': {
      id: '/api/cms/gallery'
      path: '/api/cms/gallery'
      fullPath: '/api/cms/gallery'
      preLoaderRoute: typeof ApiCmsGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/news': {
      id: '/api/cms/news'
      path: '/api/cms/news'
      fullPath: '/api/cms/news'
      preLoaderRoute: typeof ApiCmsNewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cms/pages': {
      id: '/api/cms/pages'
      path: '/api/cms/pages'
      fullPath: '/api/cms/pages'
      preLoaderRoute: typeof ApiCmsPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  ActualitesRoute: ActualitesRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  DonRoute: DonRoute,
  FaqRoute: FaqRoute,
  GouvernanceRoute: GouvernanceRoute,
  ImpactRoute: ImpactRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PdimaRoute: PdimaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminActualitesRoute: AdminActualitesRoute,
  AdminDocumentsRoute: AdminDocumentsRoute,
  AdminGalerieRoute: AdminGalerieRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPagesRoute: AdminPagesRoute,
  ApiMessagesRoute: ApiMessagesRoute,
  ApiNotifyAdminLoginRoute: ApiNotifyAdminLoginRoute,
  ApiVisitsRoute: ApiVisitsRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiCmsDocumentsRoute: ApiCmsDocumentsRoute,
  ApiCmsGalleryRoute: ApiCmsGalleryRoute,
  ApiCmsNewsRoute: ApiCmsNewsRoute,
  ApiCmsPagesRoute: ApiCmsPagesRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
